package com.bing.dao;

import com.bing.pojo.Cart;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface CartMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neuedu_cart
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neuedu_cart
     *
     * @mbg.generated
     */
    int insert(Cart record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neuedu_cart
     *
     * @mbg.generated
     */
    Cart selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neuedu_cart
     *
     * @mbg.generated
     */
    List<Cart> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neuedu_cart
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Cart record);

    Cart selectCartByUseridAndProductId(@Param("userId") Integer userId,
                                        @Param("productId") Integer productId);



    Integer deleteByUserIdAndProductIds(@Param("userId") Integer userId,
                                        @Param("productIdList") List<Integer> productIdList);

    List<Cart> selectCartByUserid(Integer userId);//查询属于userId的人的购物车集合


    Integer isCheckedAll(Integer userId);//统计未选中商品的个数

    Integer get_cart_product_count(Integer userId);

   Integer selectOrUnselectProduct(@Param("userId") Integer userId,
                                   @Param("productId") Integer productId,
                                   @Param("check") Integer check);

   List<Cart> findCartListByUserIdAndChecked(Integer userId);
   Integer batchDelete(@Param("cartList") List<Cart> cartList);

}