package com.bing.dao;

import com.bing.pojo.User;
import org.apache.ibatis.annotations.Param;


import java.util.List;

public interface UserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neuedu_user
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neuedu_user
     *
     * @mbg.generated
     */
    int insert(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neuedu_user
     *
     * @mbg.generated
     */
    User selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neuedu_user
     *
     * @mbg.generated
     */
    List<User> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neuedu_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(User record);
    /**
     *
     * 判断用户名是否存在
     *
     * */
    int isexistsusername(@Param("username") String username);
    /**
     *
     * 判断邮箱是否存在
     *
     * */
    int isexistsemail(@Param("email") String email);

    User login(@Param("username") String username,@Param("password") String password);
    String  forget_question(@Param("username") String username);
    int forget_check_answer(@Param("username") String username,@Param("question") String question,@Param("answer") String answer);
    int forget_reset_password(@Param("username") String username,@Param("newpassword") String newpassword);
    int upPassword(@Param("password") String password);
    int modifyPassword(@Param("password") String password,@Param("username") String username);
    User getInfo(@Param("username") String username);
    int isexistpassword(@Param("password") String password);
    int updaInfo(@Param("user") User user,@Param("id") int id);
}